version: 3

tasks:
  build:
    desc: "Compile library"
    cmd: go build -o ./bin/main .

  test:
    desc: "Execute tests"
    cmd: go test -v ./... -timeout 1m {{.CLI_ARGS}}

  lint:
    desc: "Check for possible errors on code"
    cmd: go vet -v ./... {{.CLI_ARGS}}
